import { useState, useEffect } from 'react';
import { supabase } from './lib/supabase';
import { toast } from 'sonner';
import { LayoutDashboard, Globe, Factory, Send, LogOut, Cpu, Zap, Car, Briefcase, Percent } from 'lucide-react';
import Auth from './components/Auth';
import Landing from './components/landing';

function App() {
  const [session, setSession] = useState(null);
  const [showAuth, setShowAuth] = useState(false);
  const [loading, setLoading] = useState(false);
  const [market, setMarket] = useState('Europe');
  const [industry, setIndustry] = useState('Robotics');
  const [prompt, setPrompt] = useState('');
  const [matches, setMatches] = useState(null);
  
  // Stati per il Modale Email
  const [selectedPartner, setSelectedPartner] = useState(null);
  const [emailContent, setEmailContent] = useState('');
  const [isGeneratingEmail, setIsGeneratingEmail] = useState(false);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => setSession(session));
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
      if (session) setShowAuth(false);
    });
    return () => subscription.unsubscribe();
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!prompt) return toast.error('Please describe your company needs!');
    setLoading(true);
    try {
      const response = await fetch('/api/match', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ market, industry, prompt })
      });
      const data = await response.json();
      setMatches(data);
      toast.success('Matches generated by GPT-5.4');
    } catch (error) {
      toast.error('AI Engine error');
    } finally {
      setLoading(false);
    }
  };

  const generateEmail = async (partner) => {
    setSelectedPartner(partner);
    setIsGeneratingEmail(true);
    setEmailContent('');
    try {
      const response = await fetch('/api/email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          partnerName: partner.name,
          partnerType: partner.type,
          country: partner.country,
          industry: industry,
          userPitch: prompt
        })
      });
      const data = await response.json();
      setEmailContent(data.text);
    } catch (error) {
      toast.error("Email generation failed");
    } finally {
      setIsGeneratingEmail(false);
    }
  };

  if (!session && !showAuth) return <Landing onNavigateToAuth={() => setShowAuth(true)} />;
  if (!session && showAuth) return (
    <div className="relative"><button onClick={() => setShowAuth(false)} className="absolute top-4 left-4 z-50 text-slate-500 font-medium">← Back</button><Auth /></div>
  );

  return (
    <div className="min-h-screen bg-[#F8FAFC] font-sans text-slate-900">
      <nav className="bg-white border-b border-slate-200 px-6 py-4 flex justify-between items-center sticky top-0 z-10 shadow-sm">
        <div className="flex items-center gap-2">
          <div className="bg-blue-600 p-2 rounded-lg text-white"><Briefcase size={20} /></div>
          <span className="text-xl font-bold tracking-tight text-slate-800">Bridge<span className="text-blue-600">Match</span></span>
        </div>
        <button onClick={() => supabase.auth.signOut()} className="flex items-center gap-2 text-slate-600 hover:text-red-600 transition-colors text-sm font-medium">
          <LogOut size={18} /> Logout
        </button>
      </nav>

      <main className="max-w-6xl mx-auto p-6 lg:p-10">
        <div className="grid lg:grid-cols-3 gap-8">
          <div className="lg:col-span-1 space-y-6">
            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
              <h2 className="text-lg font-semibold mb-4 flex items-center gap-2"><Globe size={18} className="text-blue-600" /> Target Market</h2>
              <div className="grid grid-cols-2 gap-3 mb-6">
                {['Europe', 'North America'].map((m) => (
                  <button key={m} onClick={() => setMarket(m)} className={`py-2 px-3 rounded-lg text-sm font-medium border ${market === m ? 'bg-blue-50 border-blue-600 text-blue-600' : 'bg-white border-slate-200 text-slate-600'}`}>{m}</button>
                ))}
              </div>
              <h2 className="text-lg font-semibold mb-4 flex items-center gap-2"><Factory size={18} className="text-blue-600" /> Sector</h2>
              <div className="space-y-2 mb-6">
                {['Robotics', 'EV & Battery', 'Smart Mobility'].map((i) => (
                  <button key={i} onClick={() => setIndustry(i)} className={`w-full text-left py-3 px-4 rounded-xl text-sm font-medium border ${industry === i ? 'bg-blue-50 border-blue-600 text-blue-600' : 'bg-white border-slate-200 text-slate-600'}`}>{i}</button>
                ))}
              </div>
              <form onSubmit={handleGenerate} className="space-y-4">
                <textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder="Describe your product..." className="w-full h-32 p-4 rounded-xl border border-slate-200 bg-slate-50 text-sm resize-none" />
                <button disabled={loading} className="w-full bg-slate-900 text-white py-4 rounded-xl font-bold hover:bg-slate-800 disabled:bg-slate-400">{loading ? 'Finding...' : 'Find Partners'}</button>
              </form>
            </div>
          </div>

          <div className="lg:col-span-2 space-y-4">
            {matches ? matches.map((match) => (
              <div key={match.id} className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 flex flex-col sm:flex-row gap-4 items-center">
                <div className="flex-1 text-left w-full">
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className="font-bold text-lg">{match.name}</h3>
                    <span className="px-2 py-0.5 bg-slate-100 text-slate-600 text-xs rounded-full">{match.type}</span>
                  </div>
                  <p className="text-sm text-slate-500 mb-2">📍 {match.country}</p>
                  <p className="text-sm text-slate-700">{match.reason}</p>
                </div>
                <div className="flex sm:flex-col items-center gap-3 w-full sm:w-auto">
                  <div className="bg-green-50 text-green-700 px-4 py-2 rounded-xl border border-green-100 font-bold w-full text-center tracking-tighter text-xl">%{match.score}</div>
                  <button onClick={() => generateEmail(match)} className="w-full bg-slate-900 text-white text-sm font-semibold py-2 px-4 rounded-lg hover:bg-slate-800 transition-colors">Connect</button>
                </div>
              </div>
            )) : (
              <div className="h-full min-h-[400px] flex flex-col items-center justify-center bg-white rounded-3xl border-2 border-dashed border-slate-200 text-slate-400 italic p-10">AI output will appear here</div>
            )}
          </div>
        </div>
      </main>

      {/* MODALE EMAIL AI */}
      {selectedPartner && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl shadow-2xl max-w-2xl w-full max-h-[90vh] flex flex-col">
            <div className="p-6 border-b flex justify-between items-center">
              <h3 className="text-xl font-bold text-slate-800">AI Outreach for {selectedPartner.name}</h3>
              <button onClick={() => setSelectedPartner(null)} className="text-slate-400 hover:text-slate-600 text-2xl">✕</button>
            </div>
            <div className="p-8 overflow-y-auto">
              {isGeneratingEmail ? (
                <div className="space-y-4 animate-pulse"><div className="h-4 bg-slate-100 rounded w-3/4"></div><div className="h-4 bg-slate-100 rounded w-full"></div><div className="h-4 bg-slate-100 rounded w-5/6"></div></div>
              ) : (
                <pre className="whitespace-pre-wrap font-sans text-slate-700 text-sm bg-slate-50 p-6 rounded-2xl border border-slate-100">{emailContent}</pre>
              )}
            </div>
            <div className="p-6 bg-slate-50 border-t flex gap-4">
              <button onClick={() => { navigator.clipboard.writeText(emailContent); toast.success("Copied!"); }} className="flex-1 bg-blue-600 text-white py-3 rounded-xl font-bold hover:bg-blue-700">Copy Content</button>
              <button onClick={() => setSelectedPartner(null)} className="px-6 py-3 text-slate-600 font-semibold">Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;