import { useState, useEffect } from 'react';
import { supabase } from './lib/supabase';
import { toast } from 'sonner';
import { 
  Globe, 
  Factory, 
  Send, 
  LogOut, 
  Cpu, 
  Zap, 
  Car, 
  Briefcase, 
  Percent, 
  Mail, 
  CheckCircle2 
} from 'lucide-react';
import Auth from './components/auth';
import Landing from './components/landing';

function App() {
  // --- STATI DI AUTENTICAZIONE E UI ---
  const [session, setSession] = useState(null);
  const [showAuth, setShowAuth] = useState(false);
  const [loading, setLoading] = useState(false);
  
  // --- STATI DEL FORM DI RICERCA ---
  const [market, setMarket] = useState('Europe');
  const [industry, setIndustry] = useState('Robotics');
  const [prompt, setPrompt] = useState('');
  const [matches, setMatches] = useState(null);

  // --- STATI PER IL MODALE EMAIL AI ---
  const [selectedPartner, setSelectedPartner] = useState(null);
  const [emailContent, setEmailContent] = useState('');
  const [isGeneratingEmail, setIsGeneratingEmail] = useState(false);

  // --- LOGICA DI SESSIONE SUPABASE ---
  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
      if (session) setShowAuth(false);
    });

    return () => subscription.unsubscribe();
  }, []);

  // --- FUNZIONE 1: RICERCA PARTNER (Orbit AI Matchmaker) ---
  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!prompt) return toast.error('Please describe your company needs!');
    
    setLoading(true);
    setMatches(null); // Reset dei risultati precedenti
    
    try {
      const response = await fetch('/api/match', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ market, industry, prompt })
      });

      if (!response.ok) throw new Error('AI Engine error');

      const data = await response.json();
      setMatches(data);
      toast.success('Matches generated by GPT-5.4');
    } catch (error) {
      console.error(error);
      toast.error('Failed to connect to Orbit AI');
    } finally {
      setLoading(false);
    }
  };

  // --- FUNZIONE 2: GENERAZIONE EMAIL (Orbit AI Outreach) ---
  const generateEmail = async (partner) => {
    setSelectedPartner(partner);
    setIsGeneratingEmail(true);
    setEmailContent(''); 

    try {
      const response = await fetch('/api/email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          partnerName: partner.name,
          partnerType: partner.type,
          country: partner.country,
          industry: industry,
          userPitch: prompt
        })
      });

      if (!response.ok) throw new Error('Email generation failed');

      const data = await response.json();
      setEmailContent(data.text);
    } catch (error) {
      console.error(error);
      toast.error("Could not generate outreach email");
    } finally {
      setIsGeneratingEmail(false);
    }
  };

  // --- RENDERING CONDIZIONALE (LANDING / AUTH) ---
  if (!session && !showAuth) {
    return <Landing onNavigateToAuth={() => setShowAuth(true)} />;
  }

  if (!session && showAuth) {
    return (
      <div className="relative min-h-screen bg-white">
        <button 
          onClick={() => setShowAuth(false)} 
          className="absolute top-6 left-6 z-50 text-slate-500 hover:text-slate-800 font-medium flex items-center gap-2 transition-all"
        >
          ← Back to Home
        </button>
        <Auth />
      </div>
    );
  }

  // --- INTERFACCIA PRINCIPALE (DASHBOARD) ---
  return (
    <div className="min-h-screen bg-[#F8FAFC] font-sans text-slate-900">
      {/* Navbar */}
      <nav className="bg-white border-b border-slate-200 px-6 py-4 flex justify-between items-center sticky top-0 z-40 shadow-sm">
        <div className="flex items-center gap-2">
          <div className="bg-blue-600 p-2 rounded-lg text-white shadow-md shadow-blue-100">
            <Briefcase size={20} />
          </div>
          <span className="text-xl font-bold tracking-tight text-slate-800">
            Bridge<span className="text-blue-600">Match</span>
          </span>
        </div>
        <div className="flex items-center gap-4">
          <div className="hidden md:block text-right">
            <p className="text-xs text-slate-400 font-medium uppercase tracking-wider">Logged in as</p>
            <p className="text-sm font-semibold text-slate-700">{session.user.email}</p>
          </div>
          <button 
            onClick={() => supabase.auth.signOut()} 
            className="flex items-center gap-2 bg-slate-50 text-slate-600 hover:text-red-600 hover:bg-red-50 px-4 py-2 rounded-xl transition-all text-sm font-bold border border-slate-100"
          >
            <LogOut size={18} /> Logout
          </button>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto p-6 lg:p-10">
        <div className="grid lg:grid-cols-12 gap-8">
          
          {/* Colonna Sinistra: Control Panel (4/12) */}
          <div className="lg:col-span-4 space-y-6">
            <div className="bg-white p-8 rounded-3xl shadow-sm border border-slate-200">
              <div className="mb-8">
                <h2 className="text-xl font-bold text-slate-800 mb-1">GTM Configuration</h2>
                <p className="text-sm text-slate-500">Define your expansion parameters</p>
              </div>

              {/* Market Selection */}
              <div className="mb-8">
                <label className="text-sm font-bold text-slate-700 mb-3 flex items-center gap-2 uppercase tracking-wide">
                  <Globe size={16} className="text-blue-600" /> Target Market
                </label>
                <div className="grid grid-cols-2 gap-3">
                  {['Europe', 'North America'].map((m) => (
                    <button 
                      key={m} 
                      onClick={() => setMarket(m)} 
                      className={`py-3 px-3 rounded-xl text-sm font-bold border transition-all ${
                        market === m 
                        ? 'bg-blue-600 border-blue-600 text-white shadow-lg shadow-blue-100' 
                        : 'bg-white border-slate-200 text-slate-600 hover:border-slate-300'
                      }`}
                    >
                      {m}
                    </button>
                  ))}
                </div>
              </div>

              {/* Industry Selection */}
              <div className="mb-8">
                <label className="text-sm font-bold text-slate-700 mb-3 flex items-center gap-2 uppercase tracking-wide">
                  <Factory size={16} className="text-blue-600" /> Strategic Sector
                </label>
                <div className="space-y-2">
                  {[
                    { id: 'Robotics', icon: <Cpu size={16}/> },
                    { id: 'EV & Battery', icon: <Zap size={16}/> },
                    { id: 'Smart Mobility', icon: <Car size={16}/> }
                  ].map((i) => (
                    <button 
                      key={i.id} 
                      onClick={() => setIndustry(i.id)} 
                      className={`w-full flex items-center gap-3 py-3.5 px-4 rounded-xl text-sm font-bold border transition-all ${
                        industry === i.id 
                        ? 'bg-blue-50 border-blue-600 text-blue-600' 
                        : 'bg-white border-slate-200 text-slate-600 hover:border-slate-300'
                      }`}
                    >
                      {i.icon} {i.id}
                    </button>
                  ))}
                </div>
              </div>

              {/* Pitch Input */}
              <form onSubmit={handleGenerate} className="space-y-4">
                <label className="text-sm font-bold text-slate-700 mb-1 flex items-center gap-2 uppercase tracking-wide">
                  <Send size={16} className="text-blue-600" /> Company Pitch
                </label>
                <textarea 
                  value={prompt} 
                  onChange={(e) => setPrompt(e.target.value)} 
                  placeholder="Tell GPT-5.4 about your technology and what kind of partners you need..." 
                  className="w-full h-40 p-4 rounded-2xl border border-slate-200 bg-slate-50 text-sm focus:ring-2 focus:ring-blue-500 focus:outline-none transition-all resize-none" 
                />
                <button 
                  disabled={loading} 
                  className="w-full bg-slate-900 text-white py-4 rounded-2xl font-bold flex items-center justify-center gap-3 hover:bg-slate-800 transition-all disabled:bg-slate-300 shadow-xl shadow-slate-200 active:scale-[0.98]"
                >
                  {loading ? (
                    <div className="flex items-center gap-2">
                      <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                      Analysing Market...
                    </div>
                  ) : (
                    <>Generate AI Matches</>
                  )}
                </button>
              </form>
            </div>
          </div>

          {/* Colonna Destra: Risultati (8/12) */}
          <div className="lg:col-span-8 space-y-4">
            {matches ? (
              <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-700">
                <div className="flex items-center justify-between mb-2 px-2">
                  <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                    <CheckCircle2 size={20} className="text-green-500" /> 
                    Top 3 Partner Matches
                  </h3>
                  <span className="text-xs font-bold text-blue-600 bg-blue-50 px-3 py-1 rounded-full uppercase">Orbit AI Engine 5.4</span>
                </div>
                
                {matches.map((match) => (
                  <div key={match.id} className="bg-white p-6 rounded-3xl shadow-sm border border-slate-200 flex flex-col md:flex-row gap-6 items-center hover:border-blue-400 hover:shadow-md transition-all group">
                    <div className="flex-1 text-left w-full">
                      <div className="flex items-center gap-3 mb-2">
                        <h3 className="font-bold text-xl text-slate-900 group-hover:text-blue-700 transition-colors">{match.name}</h3>
                        <span className="px-3 py-1 bg-slate-100 text-slate-500 text-[10px] font-black uppercase tracking-tighter rounded-lg border border-slate-200">
                          {match.type}
                        </span>
                      </div>
                      <p className="text-sm font-bold text-blue-600/70 mb-3 flex items-center gap-1">
                        📍 {match.country}
                      </p>
                      <p className="text-sm text-slate-600 leading-relaxed font-medium">
                        {match.reason}
                      </p>
                    </div>
                    
                    <div className="flex md:flex-col items-center gap-3 w-full md:w-32">
                      <div className="flex-1 md:w-full bg-green-50 text-green-700 p-3 rounded-2xl border border-green-100 flex flex-col items-center justify-center">
                        <span className="text-[10px] font-black uppercase tracking-widest opacity-60">Match</span>
                        <div className="text-2xl font-black flex items-center tracking-tighter">
                          <Percent size={18} strokeWidth={3} />{match.score}
                        </div>
                      </div>
                      <button 
                        onClick={() => generateEmail(match)} 
                        className="flex-[2] md:w-full bg-slate-900 text-white text-sm font-bold py-3 px-4 rounded-2xl hover:bg-blue-600 transition-all flex items-center justify-center gap-2 shadow-lg shadow-slate-100"
                      >
                        <Mail size={16} /> Connect
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="h-full min-h-[500px] flex flex-col items-center justify-center bg-white rounded-[2.5rem] border-2 border-dashed border-slate-200 text-center p-12">
                <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center mb-6 text-slate-300">
                  <Briefcase size={40} />
                </div>
                <h3 className="text-2xl font-bold text-slate-800 mb-2">Ready to expand?</h3>
                <p className="text-slate-400 max-w-sm font-medium leading-relaxed">
                  Enter your company details on the left and let our AI scout the best Western partners for your GTM strategy.
                </p>
              </div>
            )}
          </div>
        </div>
      </main>

      {/* --- MODALE AI OUTREACH ASSISTANT --- */}
      {selectedPartner && (
        <div className="fixed inset-0 bg-slate-900/80 backdrop-blur-md z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-[2rem] shadow-2xl max-w-2xl w-full max-h-[90vh] flex flex-col overflow-hidden animate-in zoom-in-95 duration-300">
            
            {/* Header Modale */}
            <div className="p-8 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
              <div className="flex items-center gap-3">
                <div className="bg-blue-600 p-2 rounded-lg text-white">
                  <Mail size={20} />
                </div>
                <div>
                  <h3 className="text-xl font-black text-slate-800 tracking-tight">AI Outreach</h3>
                  <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Tailored for {selectedPartner.name}</p>
                </div>
              </div>
              <button 
                onClick={() => setSelectedPartner(null)} 
                className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-slate-200 text-slate-400 transition-all text-xl"
              >
                ✕
              </button>
            </div>

            {/* Content Modale */}
            <div className="p-8 overflow-y-auto bg-white flex-1">
              {isGeneratingEmail ? (
                <div className="space-y-6 animate-pulse">
                  <div className="space-y-2">
                    <div className="h-3 bg-slate-100 rounded-full w-1/4"></div>
                    <div className="h-10 bg-slate-50 rounded-xl w-full"></div>
                  </div>
                  <div className="space-y-3">
                    <div className="h-3 bg-slate-100 rounded-full w-1/5"></div>
                    <div className="h-4 bg-slate-50 rounded-full w-full"></div>
                    <div className="h-4 bg-slate-50 rounded-full w-5/6"></div>
                    <div className="h-4 bg-slate-50 rounded-full w-4/5"></div>
                  </div>
                </div>
              ) : (
                <div className="relative group">
                  <div className="absolute -top-3 -left-3 bg-blue-50 text-blue-600 text-[10px] font-black px-2 py-1 rounded shadow-sm">GPT-5.4 DRAFT</div>
                  <pre className="whitespace-pre-wrap font-mono text-slate-700 text-sm bg-slate-50 p-8 rounded-3xl border border-slate-100 leading-relaxed shadow-inner overflow-x-hidden min-h-[300px]">
                    {emailContent}
                  </pre>
                </div>
              )}
            </div>

            {/* Footer Modale */}
            <div className="p-8 bg-slate-50 border-t border-slate-100 flex flex-col sm:flex-row gap-4">
              <button 
                disabled={isGeneratingEmail}
                onClick={() => { 
                  navigator.clipboard.writeText(emailContent); 
                  toast.success("Ready to send! Copied to clipboard."); 
                }} 
                className="flex-1 bg-blue-600 text-white py-4 rounded-2xl font-black hover:bg-blue-700 transition-all shadow-lg shadow-blue-200 active:scale-95 disabled:opacity-50"
              >
                Copy Outreach Email
              </button>
              <button 
                onClick={() => setSelectedPartner(null)} 
                className="px-8 py-4 text-slate-500 font-bold hover:text-slate-800 transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;